environment:
  matrix:
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.8
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.9
      MINICONDA: C:\Miniconda3

cache:
    - "%MINICONDA%\\envs -> appveyor.yml, setup.py"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose"
  - activate test-environment
  - pip install --upgrade setuptools
  - pip install matplotlib
  - pip install pytest-cov
  - pip install pytest
  - pip install codecov
  - pip install coveralls
  - pip install pytest-xdist
  - pip install codacy-coverage
  - pip install numpy
  - pip install scipy
  - pip install Cython==0.29.21

build: off
test_script:
  - pytest --cache-clear -n 8 -q --cov=./spafe tests/test_*.py
